# Generated by Django 2.1 on 2021-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='attorney',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='attorney_firm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='attorney_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='broker',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='broker_firm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='broker_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='buyer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='buyer_firm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='buyer_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='county',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='downpay',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='lender',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='lender_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='loan_office',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='lot_no',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='matter_no',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='matter_ref',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='property',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='purchase',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='seller',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='seller_firm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='seller_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='staff',
            field=models.TextField(blank=True, default=''),
        ),
    ]
