# Generated by Django 3.2.7 on 2021-10-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion4', '0002_auto_20210926_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_ref', models.TextField(blank=True, default='')),
                ('code', models.TextField(blank=True, default='')),
                ('matter_no', models.IntegerField(blank=True, default='')),
                ('county', models.TextField(blank=True, default='')),
                ('staff', models.TextField(blank=True, default='')),
                ('buyer', models.TextField(blank=True, default='')),
                ('buyer_firm', models.TextField(blank=True, default='')),
                ('buyer_phone', models.TextField(blank=True, default='')),
                ('seller', models.TextField(blank=True, default='')),
                ('seller_firm', models.TextField(blank=True, default='')),
                ('seller_phone', models.TextField(blank=True, default='')),
                ('client', models.TextField(blank=True, default='')),
                ('property', models.TextField(blank=True, default='')),
                ('lot_no', models.TextField(blank=True, default='')),
                ('purchase', models.TextField(blank=True, default='')),
                ('downpay', models.TextField(blank=True, default='')),
                ('attorney', models.TextField(blank=True, default='')),
                ('attorney_firm', models.TextField(blank=True, default='')),
                ('attorney_phone', models.TextField(blank=True, default='')),
                ('lender', models.TextField(blank=True, default='')),
                ('loan_office', models.TextField(blank=True, default='')),
                ('lender_phone', models.TextField(blank=True, default='')),
                ('broker', models.TextField(blank=True, default='')),
                ('broker_firm', models.TextField(blank=True, default='')),
                ('broker_phone', models.TextField(blank=True, default='')),
            ],
        ),
    ]
