# Generated by Django 3.2.7 on 2021-11-01 04:29

from django.db import migrations
import csv

def import_standard_records(apps, schmea_editor):
    Standard_Record= apps.get_model('lion4', 'Standard_Record')
    fields=[field.name for field in Standard_Record._meta.get_fields()]

    with open('standard_records.csv', newline='') as csv_file:
        csv_reader=csv.reader(csv_file)
        line_count =0
        for row in csv_reader:
            if line_count >0:
                new_record= Standard_Record()
                for count, field in enumerate(fields):
                    if count ==0:
                        pass
                    elif count==3:
                        setattr(new_record, field, int(row[count]))
                    else:
                        setattr(new_record, field, row[count])

                new_record.save()
            line_count+=1



class Migration(migrations.Migration):

    dependencies = [
        ('lion4', '0003_standard_record'),
    ]

    operations = [
            migrations.RunPython(import_standard_records),
    ]
