# Generated by Django 3.2.7 on 2021-11-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion4', '0004_auto_20211101_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_record',
            name='attorney_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='broker_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='buyer_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='lender_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='seller_email',
            field=models.TextField(blank=True, default=''),
        ),
    ]
