# Generated by Django 3.2.7 on 2022-03-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion4', '0005_auto_20211130_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_record',
            name='date_opened',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='sellers_broker',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='sellers_broker_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='sellers_broker_firm',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standard_record',
            name='sellers_broker_phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
