# Generated by Django 3.2.7 on 2021-12-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lion4', '0006_auto_20211218_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_contact',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lion4.record'),
        ),
    ]
